<a href="https://colab.research.google.com/github/25WH1A05AN/NASSCOMM/blob/main/Pandas_Exercise%20(1).ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert the array into a DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame:")
print(df1_3)


# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': pd.date_range('2023-01-01', periods=100),
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100).astype(float),
    'Quantity': np.random.randint(1, 11, 100).astype(float)
})

# Introduce NaN values
sales_nan = np.random.choice(df_sales.index, 5, replace=False)
qty_nan = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan, 'Sales'] = np.nan
df_sales.loc[qty_nan, 'Quantity'] = np.nan

print(df_sales.head())


# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]
# 3.2 Rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

# 3.3 Region is East and Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

# 3.4 Sales value for first Monitor entry
monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]
val3_4 = df_sales.loc[monitor_index, 'Sales']

print("\ndf3_1:")
print(df3_1.head())

print("\ndf3_2:")
print(df3_2.head())

print("\ndf3_3:")
print(df3_3.head())

print("\nFirst Monitor Sales:", val3_4)


# Task 4: Data Cleaning (Handling Missing Value)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Count missing values
missing_counts4_1 = df_sales.isnull().sum()

# 4.2 Fill missing Sales with mean
df4_2_filled = df_sales.copy()
mean_sales = df4_2_filled['Sales'].mean()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(mean_sales)

# 4.3 Drop rows containing any NaN
df4_3_dropped = df_sales.dropna()

print("Missing Values:")
print(missing_counts4_1)

print("\nSales column after filling NaNs:")
print(df4_2_filled.head())

print("\nData after dropping NaNs:")
print(df4_3_dropped.head())

# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

# 5.3 Group by Region
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

# 5.4 Group by Product
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\nData with Total_Revenue:")
print(df_sales.head())

print("\nSorted Data:")
print(df5_2_sorted.head())

print("\nGrouped by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[72 22 13 75]
 [ 9 58 19 28]
 [51 97 75 77]]

DataFrame:
    A   B   C   D
0  72  22  13  75
1   9  58  19  28
2  51  97  75  77

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  South    Laptop  678.0       9.0
1 2023-01-02   West   Monitor  678.0       8.0
2 2023-01-03  North     Mouse  162.0       2.0
3 2023-01-04   East  Keyboard  440.0       9.0
4 2023-01-05  North  Keyboard  747.0       1.0

--- Task 3: Indexing and Slicing in DataFrames ---

df3_1:
  Region  Sales
0  South  678.0
1   West  678.0
2  North  162.0
3   East  440.0
4  North  747.0

df3_2:
         Date Region Product  Sales  Quantity
0  2023-01-01  South  Laptop  678.0     